source 'https://rubygems.org'

gem 'rails', '~> 4.1.0'
gem '3scale'
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'activerecord-jdbcsqlite3-adapter', '~> 1.2.9', :platforms => [ :jruby ]
gem 'jquery-rails', '~> 3.0.0'
gem 'grape'
gem 'uglifier', '>= 1.0.3'
gem 'zip-zip', '~> 0.2'
gem 'mysql2'
gem 'devise'

group :development, :test do
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails', '~> 3.0'
  gem 'capybara', '~> 2.3.0'
  gem 'selenium-webdriver', '~> 2.42.0'
  gem 'rubocop', '~> 0.24.1'
end
